table dim_Products
	lineageTag: c8f778be-0706-4caa-ba39-a1f0404d86ac

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 853b3209-7b4e-4989-b0af-c925dded0721
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: d19dc621-d824-446c-887f-a99726b6907c
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 4135b6b2-4a2a-4ff7-88a7-9b8f0a9da374
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column StandardCost
		dataType: double
		lineageTag: d5eaf8e3-fe47-438c-9a7a-187e9bd590a8
		summarizeBy: none
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Color
		dataType: string
		lineageTag: 25796c62-cfec-4c62-991e-d73ed96a63da
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column SafetyStockLevel
		dataType: int64
		formatString: 0
		lineageTag: cfbaf3fc-5c91-4e5d-b4b4-fc233c054f62
		summarizeBy: none
		sourceColumn: SafetyStockLevel

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: double
		lineageTag: 9015835c-717e-43cd-8324-51a7afc18390
		summarizeBy: none
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Size
		dataType: int64
		formatString: 0
		lineageTag: a54330af-ac53-43d7-be11-faf08bf4b5d6
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column SizeRange
		dataType: string
		lineageTag: c8300f2b-0040-4106-adf6-d1f1fd4435c8
		summarizeBy: none
		sourceColumn: SizeRange

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 04525c9c-8122-43ff-b27d-b530444d6831
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DaysToManufacture
		dataType: int64
		formatString: 0
		lineageTag: 45a2a462-9a7b-4d09-94a1-34a285003788
		summarizeBy: none
		sourceColumn: DaysToManufacture

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 50785925-444f-4d0a-911f-4963273da59c
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column DealerPrice
		dataType: double
		lineageTag: 25c589b6-bb3c-4be1-904b-df0ef5afcf04
		summarizeBy: none
		sourceColumn: DealerPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Class
		dataType: string
		lineageTag: a70b2a04-4bc1-4b40-a426-8d9d42066ad7
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: 93506d06-d60c-4925-b87e-59b8a515f0ca
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 0e6cddf1-cf55-4ba7-862f-a8604af4c56d
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1126e048-cefd-4830-a0a6-05d7ea53a4e0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: b00c22f6-4ebb-4220-b28f-6a00225a0164
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1d15306f-eb7c-4186-bfc4-c387b6a66826
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9bcba0d-51f3-469c-b7a9-6d9285de40f8
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb9131d5-abc9-4bee-9b40-05fbe5b37146
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_Products-7ad5312c-0798-456e-b25b-5686c8bbc74b = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://ibm-my.sharepoint.com/personal/rideb184_in_ibm_com/Documents/Desktop/Work%20In%20Progress/14.%20Service%20Line/Book-760/Sample%20Data/Adventure%20Works%202020.xlsx"), null, true),
				    Products_Sheet = Source{[Item="Products",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductName", type text}, {"StandardCost", type number}, {"Color", type text}, {"SafetyStockLevel", Int64.Type}, {"ListPrice", type number}, {"Size", Int64.Type}, {"SizeRange", type text}, {"Weight", type number}, {"DaysToManufacture", Int64.Type}, {"ProductLine", type text}, {"DealerPrice", type number}, {"Class", type text}, {"ModelName", type text}, {"Description", type text}, {"Status", type text}, {"SubCategory", type text}, {"Category", type text}, {"StartDate", type date}, {"EndDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

